spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          auth: true
    host: smtp.gmail.com
    username: hostinglnx@gmail.com  
    password: ################
    port: 587